backend:
  name: git-gateway

media_folder: static/assets
public_folder: /assets

collections:
  - label: 'Menu Item'
    name: 'menu item'
    folder: 'src/data/menu'
    create: true
    fields:
      - label: 'Label'
        name: label
      - label: 'Link'
        name: link
        hint: 'Can be relative path (common, i.e. `/projects/prj-a`) or absolute (for external sites, i.e. `http://example.com` )'
      - label: 'Is External'
        name: isExternal
        widget: boolean
        hint: 'Indicate if is external link'
      - label: 'Order'
        name: order
        widget: number
        hint: Number to indicate order it should appear
  - label: 'Project Detail'
    name: 'project detail'
    folder: 'src/data/projects'
    create: true
    fields:
      - label: 'ID'
        name: 'id'
      - label: 'Path'
        name: 'path'
        hint: 'Path to project page. i.e., `/client-a` is accessible at `mysite.com/client-a`'
        pattern: ['^(\/([\w-]{1,}))+', 'Start with a forward slash and not include whitespace']
      - label: 'Title'
        name: 'title'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
      - label: 'Images'
        name: 'images'
        widget: 'list'
        field: { label: Image, name: image, widget: image }
      - label: 'IFrame'
        name: 'iframe'
        required: false
  - label: 'Galleries'
    name: 'galleries'
    files:
      - label: 'Homepage'
        name: 'homepage'
        file: 'src/data/galleries/homepage/index.md'
        fields:
          - label: 'Images'
            name: 'imageList'
            widget: 'list'
            fields:
              - label: 'Project Detail Path'
                name: 'path'
                widget: relation
                collection: 'project detail'
                searchFields: [path]
                valueField: path
                required: false
                hint: 'Must match Project detail path'
              - label: 'Image'
                name: 'image'
                widget: image
              - label: 'Order'
                name: order
                widget: number
                hint: Top-Bottom then Left-Right
      - label: 'Illustrations'
        name: 'illustrations'
        file: 'src/data/galleries/illustrations/index.md'
        fields:
          - label: 'Images'
            name: 'illustrationImagesAndDetails'
            widget: 'list'
            fields:
              - label: 'Title'
                name: 'title'
              - label: 'Subitle'
                name: 'subtitle'
              - label: 'Image'
                name: 'image'
                widget: image
              - label: 'Order'
                name: order
                widget: number
                hint: Left-Right then Top-Bottom