backend:
  name: git-gateway
  repo: galenom/cms-config

media_folder: static/assets
public_folder: /assets

collections:
  - label: "Project Detail"
    name: "project detail"
    folder: "project/"
    create: true
    fields:
      - { label: "ID", name: "id" }
      - { label: "Path", name: "path" } 
      - { label: "Title", name: "title" }
      - { label: "Body", name: "body", widget: 'markdown'}
      - label: "gallery"
        name: "gallery"
        widget: "list"
        field: { label: Image, name: image, widget: image }

